name: Deploy to Amazon EC2

on:
  push:
    branches: [ "solution" ]

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: efub-blog
  CODE_DEPLOY_APPLICATION_NAME: efub-blog-codedeploy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: efub-blog-codedeploy-deployment-group-2

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Print working directory
        run: pwd

      - name: List directory contents
        run: ls -la

      - name: List blog directory contents
        run: ls -la blog

      - name: make application.yml
        run: |
          mkdir -p blog/src/main/resources
          touch blog/src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_YML }}" > blog/src/main/resources/application.yml

      - name: Build with Gradle
        working-directory: blog
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to AWS S3
        working-directory: blog
        run: |
          echo "Pushing to S3: s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip"
          aws deploy push \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --ignore-hidden-files \
            --s3-location s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip \
            --source .

      - name: Deploy to AWS EC2 from S3
        working-directory: blog
        run: |
          echo "Creating deployment with group: $CODE_DEPLOY_DEPLOYMENT_GROUP_NAME"
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip
